services:
  app-db:
    image: mysql:8
    command: 
      --collation-server=utf8mb4_0900_bin
      --transaction-isolation=READ-COMMITTED
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_USER: root1
      MYSQL_DATABASE: app
      TZ: Asia/Tokyo
    ports:
      - 53306:3306
